/**
 * pages/PendingOrders.tsx — Pending Orders (Salesman Generated)
 *
 * Shows orders generated by salesmen that need to be finalized by owner/manager/cashier.
 * Uses status='draft' + salesman_name IS NOT NULL to distinguish from regular drafts.
 */
import React, { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { EmptyState, TableSkeleton } from '@/components/ui/EmptyState';
import {
  Table, TableBody, TableCell, TableHead, TableHeader, TableRow,
} from '@/components/ui/table';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { Clock, Search, User, ShoppingCart, Check, Loader2 } from 'lucide-react';
import { format } from 'date-fns';
import { toast } from 'sonner';
import DraftBillModal from '@/components/bills/DraftBillModal';

export default function PendingOrders() {
  const { businessId, user, userRole } = useAuth();
  const queryClient = useQueryClient();
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedBillId, setSelectedBillId] = useState<string | null>(null);

  const { data: pendingOrders = [], isLoading } = useQuery({
    queryKey: ['pendingOrders', businessId, user?.id, userRole],
    queryFn: async () => {
      let query = (supabase as any)
        .from('bills')
        .select('*, customers(name, phone, address)')
        .eq('business_id', businessId!)
        .eq('status', 'draft')
        .not('salesman_name', 'is', null)
        .order('created_at', { ascending: false });

      // Salesman sees only their own orders
      if (userRole === 'salesman') {
        query = query.eq('created_by', user?.id);
      }

      const { data, error } = await query;
      if (error) throw error;
      return data;
    },
    enabled: !!businessId,
  });

  const filteredOrders = pendingOrders.filter(bill =>
    bill.bill_number.toLowerCase().includes(searchTerm.toLowerCase()) ||
    (bill.customers?.name || '').toLowerCase().includes(searchTerm.toLowerCase()) ||
    (bill.salesman_name || '').toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <div className="flex flex-col gap-5">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h1 className="spos-page-heading">Pending Orders</h1>
          <p className="spos-page-subhead mb-0">
            Orders generated by salesmen that need to be finalized.
          </p>
        </div>
        <Badge variant="outline" className="text-sm px-3 py-1">
          {pendingOrders.length} pending
        </Badge>
      </div>

      <div className="relative w-full sm:max-w-sm">
        <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
        <Input
          placeholder="Search order, customer, or salesman..."
          className="pl-8"
          value={searchTerm}
          onChange={(e) => setSearchTerm(e.target.value)}
        />
      </div>

      <Card>
        <CardHeader className="pb-3">
          <CardTitle>Pending Orders</CardTitle>
          <CardDescription>
            {userRole === 'salesman'
              ? 'Your generated orders awaiting finalization.'
              : 'Click "Open" to review and finalize an order.'}
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="rounded-md border">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Order No.</TableHead>
                  <TableHead>Customer</TableHead>
                  <TableHead>Amount</TableHead>
                  <TableHead className="hidden md:table-cell">Date</TableHead>
                  <TableHead className="hidden sm:table-cell">Salesman</TableHead>
                  <TableHead className="text-right">Action</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {isLoading ? (
                  <TableRow>
                    <TableCell colSpan={6} className="p-0">
                      <TableSkeleton columns={6} rows={4} />
                    </TableCell>
                  </TableRow>
                ) : filteredOrders.length === 0 ? (
                  <TableRow>
                    <TableCell colSpan={6} className="p-0">
                      <EmptyState
                        icon="drafts"
                        title="No pending orders"
                        description="When salesmen generate orders, they will appear here for finalization."
                      />
                    </TableCell>
                  </TableRow>
                ) : (
                  filteredOrders.map((bill) => (
                    <TableRow key={bill.id}>
                      <TableCell className="font-medium text-xs sm:text-sm">
                        <div className="flex items-center gap-2">
                          <ShoppingCart className="h-4 w-4 text-amber-500 hidden sm:block" />
                          {bill.bill_number}
                        </div>
                      </TableCell>
                      <TableCell className="text-xs sm:text-sm truncate max-w-[80px] sm:max-w-none">
                        <div className="flex flex-col">
                          <span className="font-medium">{bill.customers?.name || 'Walk-in'}</span>
                          <span className="text-[10px] text-muted-foreground">{bill.customers?.phone || ''}</span>
                        </div>
                      </TableCell>
                      <TableCell className="font-semibold text-primary text-xs sm:text-sm">
                        ₹{bill.total_amount.toFixed(2)}
                      </TableCell>
                      <TableCell className="hidden md:table-cell text-muted-foreground text-xs sm:text-sm">
                        <div className="flex items-center gap-1">
                          <Clock className="h-3 w-3" />
                          {format(new Date(bill.created_at), 'dd MMM, hh:mm a')}
                        </div>
                      </TableCell>
                      <TableCell className="hidden sm:table-cell text-xs sm:text-sm">
                        <Badge variant="outline" className="font-normal text-[10px] bg-primary/5">
                          <User className="mr-1 h-3 w-3" />
                          {bill.salesman_name || 'Unknown'}
                        </Badge>
                      </TableCell>
                      <TableCell className="text-right">
                        <Button
                          variant="outline"
                          size="sm"
                          onClick={() => setSelectedBillId(bill.id)}
                        >
                          <span className="sm:hidden">Open</span>
                          <span className="hidden sm:inline">Open & Finalize</span>
                        </Button>
                      </TableCell>
                    </TableRow>
                  ))
                )}
              </TableBody>
            </Table>
          </div>
        </CardContent>
      </Card>

      {selectedBillId && (
        <DraftBillModal
          billId={selectedBillId}
          open={!!selectedBillId}
          onClose={() => setSelectedBillId(null)}
        />
      )}
    </div>
  );
}
