// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error("CRITICAL: Supabase environment variables VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY are missing. Please configure them in your deployment environment settings.");
}

export const supabase = (SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY)
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
        // Detect session from URL hash on OAuth callback (needed for Capacitor deep links)
        detectSessionInUrl: true,
      }
    })
  : new Proxy({} as any, {
      get: (_, prop) => {
        throw new Error(`Supabase client is not initialized because environment variables (VITE_SUPABASE_URL, VITE_SUPABASE_PUBLISHABLE_KEY) are missing in the build environment. Prop accessed: ${String(prop)}`);
      }
    });